Update my_init

diff --git a/bin/my_init b/bin/my_init
--- a/bin/my_init
+++ b/bin/my_init
@@ -61,7 +61,7 @@ run_command () {
         retval=$?
         if [ $retval != 0 ];
         then
-            echo >&2 "*** Failed with return value: $?"
+            echo >&2 "*** Failed with return value: $retval"
             exit $retval
          else
             import_envvars
